### PR TITLE
Add farming commands 

### LINKED ISSUE #8: Basic farming commands
- [x] Harvest
- [x] Plant
- [x] Water

- As a User: Run a harvest command, which can optionally use per tile or all
- As a User: Run a plant command, which can optionally use per tile or all, depending if you have the seeds
- As a User: Run a water command, which can optionally use per tile or all, depending on the amount of water left for the day

### PR DESCRIPTION
**Pull request by HRAND5**
Basic farming commands including {prefix}harvest, {prefix}water and {prefix}plant. 

close #8

### CODE REVIEW

**Review by TheCatster — CHANGES_REQUESTED** [review]
Please fix the linting errors, in particular your usage of is not versus !=

**Review by makupi — CHANGES_REQUESTED** [review]
All three commands have very repetitive code. Please adhere to the DRY principle and maybe use a function to do the plot coordinate checks.

**Comment by HRAND5** [comment]
@TheCatster Linting errors should be fixed now. 

@makupi Code is more readable now imo. Got the regular expression method to work both ways, and now plot size is limited by size of int and not size of alphabet. Also plot does not have to be square. All rows/columns just need to have the same length.

**Review by TheCatster — APPROVED** [review]

**Review by TheCatster — CHANGES_REQUESTED** [review]
Please condense your commits, it isn't necessary or proper to have 13 commits for 4 commands. You don't need to keep a single commit for each "oops fixed bug." Please squash your commits appropriately.

**Review by makupi — APPROVED** [review]

**Review by TheCatster — APPROVED** [review]
Approve of these changes, go ahead and merge.

**Pull request merged**
