### PR TITLE
Set Defaults For Models

### LINKED ISSUE #35: Define default values for Database Tables

### PR DESCRIPTION
**Pull request by TheCatster**
The only model needing a default was Player, so it is the only one changed. Added defaults for balance, xp, energy, level, and allow_notifications.

### CODE REVIEW

**Review by makupi — COMMENTED** [review]
Everyone should probably start out with a base-balance right? Other than that looks fine.

**Comment by TheCatster** [comment]
Base balance should be zero, it encourages people to plant their seeds right away (I'm not sure how we're handling that yet, but everyone should start with 9 base-level seeds)

**Comment by makupi** [comment]
> Base balance should be zero, it encourages people to plant their seeds right away (I'm not sure how we're handling that yet, but everyone should start with 9 base-level seeds)

Just thinking that setting "default" entries for the inventory would be more complicated than giving them the money to purchase the first few seeds themselves. But both methods work.

**Comment by ferociouskyle** [comment]
> > Base balance should be zero, it encourages people to plant their seeds right away (I'm not sure how we're handling that yet, but everyone should start with 9 base-level seeds)
> 
> Just thinking that setting "default" entries for the inventory would be more complicated than giving them the money to purchase the first few seeds themselves. But both methods work.

Could you not, when the profile is created, just insert items into their inventory? 

Yes both methods solve the issue. However, while it is easier to add a balance, we should give the users seeds to encourage them to play the base game.

**Comment by makupi** [comment]
> > > Base balance should be zero, it encourages people to plant their seeds right away (I'm not sure how we're handling that yet, but everyone should start with 9 base-level seeds)
> > 
> > 
> > Just thinking that setting "default" entries for the inventory would be more complicated than giving them the money to purchase the first few seeds themselves. But both methods work.
> 
> Could you not, when the profile is created, just insert items into their inventory?
> 
> Yes both methods solve the issue. However, while it is easier to add a balance, we should give the users seeds to encourage them to play the base game.

Yes, of course you could - but that'd mean more database operations once the user is created. But yeah, we'll find some way to handle both methods.

**Comment by ferociouskyle** [comment]
I am kind of in agreement with @makupi right now. I think if we give the users coins, they will have to go out and buy from the store. It will make our lives a bit easier, so they will have to learn to use the store right from the beginning.

**Pull request merged**
